# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\x08\x61lpha_go\"2\n\x17ReloadCheckpointRequest\x12\x17\n\x0f\x63heckpoint_path\x18\x01 \x01(\t\"B\n\x18ReloadCheckpointResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\"2\n\x16LoadCheckpointsRequest\x12\x18\n\x10\x63heckpoint_paths\x18\x01 \x03(\t\"Y\n\x17LoadCheckpointsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x16\n\x0e\x63heckpoint_ids\x18\x03 \x03(\t\"Z\n\x0f\x45valuateRequest\x12\r\n\x05\x62oard\x18\x01 \x03(\x05\x12\x12\n\nboard_size\x18\x02 \x01(\x05\x12\r\n\x05\x64ummy\x18\x03 \x01(\x08\x12\x15\n\rcheckpoint_id\x18\x04 \x01(\t\"V\n\x10\x45valuateResponse\x12\x15\n\rpolicy_logits\x18\x01 \x03(\x02\x12\x13\n\x0bvalue_logit\x18\x02 \x01(\x02\x12\x16\n\x0epolicy_entropy\x18\x03 \x01(\x02\"<\n\x14\x45valuateBatchRequest\x12$\n\x06\x62oards\x18\x01 \x03(\x0b\x32\x14.alpha_go.BoardState\"F\n\nBoardState\x12\r\n\x05\x62oard\x18\x01 \x03(\x05\x12\x12\n\nboard_size\x18\x02 \x01(\x05\x12\x15\n\rcheckpoint_id\x18\x03 \x01(\t\"?\n\x15\x45valuateBatchResponse\x12&\n\x07results\x18\x01 \x03(\x0b\x32\x15.alpha_go.PolicyValue\"\x96\x01\n\x0bPolicyValue\x12\x31\n\x06policy\x18\x01 \x03(\x0b\x32!.alpha_go.PolicyValue.PolicyEntry\x12\r\n\x05value\x18\x02 \x01(\x02\x12\x16\n\x0epolicy_entropy\x18\x03 \x01(\x02\x1a-\n\x0bPolicyEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x32\xd5\x02\n\x0bNNInference\x12\x41\n\x08\x45valuate\x12\x19.alpha_go.EvaluateRequest\x1a\x1a.alpha_go.EvaluateResponse\x12P\n\rEvaluateBatch\x12\x1e.alpha_go.EvaluateBatchRequest\x1a\x1f.alpha_go.EvaluateBatchResponse\x12Y\n\x10ReloadCheckpoint\x12!.alpha_go.ReloadCheckpointRequest\x1a\".alpha_go.ReloadCheckpointResponse\x12V\n\x0fLoadCheckpoints\x12 .alpha_go.LoadCheckpointsRequest\x1a!.alpha_go.LoadCheckpointsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POLICYVALUE_POLICYENTRY']._loaded_options = None
  _globals['_POLICYVALUE_POLICYENTRY']._serialized_options = b'8\001'
  _globals['_RELOADCHECKPOINTREQUEST']._serialized_start=29
  _globals['_RELOADCHECKPOINTREQUEST']._serialized_end=79
  _globals['_RELOADCHECKPOINTRESPONSE']._serialized_start=81
  _globals['_RELOADCHECKPOINTRESPONSE']._serialized_end=147
  _globals['_LOADCHECKPOINTSREQUEST']._serialized_start=149
  _globals['_LOADCHECKPOINTSREQUEST']._serialized_end=199
  _globals['_LOADCHECKPOINTSRESPONSE']._serialized_start=201
  _globals['_LOADCHECKPOINTSRESPONSE']._serialized_end=290
  _globals['_EVALUATEREQUEST']._serialized_start=292
  _globals['_EVALUATEREQUEST']._serialized_end=382
  _globals['_EVALUATERESPONSE']._serialized_start=384
  _globals['_EVALUATERESPONSE']._serialized_end=470
  _globals['_EVALUATEBATCHREQUEST']._serialized_start=472
  _globals['_EVALUATEBATCHREQUEST']._serialized_end=532
  _globals['_BOARDSTATE']._serialized_start=534
  _globals['_BOARDSTATE']._serialized_end=604
  _globals['_EVALUATEBATCHRESPONSE']._serialized_start=606
  _globals['_EVALUATEBATCHRESPONSE']._serialized_end=669
  _globals['_POLICYVALUE']._serialized_start=672
  _globals['_POLICYVALUE']._serialized_end=822
  _globals['_POLICYVALUE_POLICYENTRY']._serialized_start=777
  _globals['_POLICYVALUE_POLICYENTRY']._serialized_end=822
  _globals['_NNINFERENCE']._serialized_start=825
  _globals['_NNINFERENCE']._serialized_end=1166
# @@protoc_insertion_point(module_scope)
