# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from alpha_go.proto import inference_pb2 as inference__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NNInferenceStub(object):
    """Neural network inference service for batched evaluation
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Evaluate = channel.unary_unary(
                '/alpha_go.NNInference/Evaluate',
                request_serializer=inference__pb2.EvaluateRequest.SerializeToString,
                response_deserializer=inference__pb2.EvaluateResponse.FromString,
                _registered_method=True)
        self.EvaluateBatch = channel.unary_unary(
                '/alpha_go.NNInference/EvaluateBatch',
                request_serializer=inference__pb2.EvaluateBatchRequest.SerializeToString,
                response_deserializer=inference__pb2.EvaluateBatchResponse.FromString,
                _registered_method=True)
        self.ReloadCheckpoint = channel.unary_unary(
                '/alpha_go.NNInference/ReloadCheckpoint',
                request_serializer=inference__pb2.ReloadCheckpointRequest.SerializeToString,
                response_deserializer=inference__pb2.ReloadCheckpointResponse.FromString,
                _registered_method=True)
        self.LoadCheckpoints = channel.unary_unary(
                '/alpha_go.NNInference/LoadCheckpoints',
                request_serializer=inference__pb2.LoadCheckpointsRequest.SerializeToString,
                response_deserializer=inference__pb2.LoadCheckpointsResponse.FromString,
                _registered_method=True)


class NNInferenceServicer(object):
    """Neural network inference service for batched evaluation
    """

    def Evaluate(self, request, context):
        """Evaluate a single board state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluateBatch(self, request, context):
        """Evaluate a batch of board states
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReloadCheckpoint(self, request, context):
        """Reload model from checkpoint (blocks all Evaluate calls during reload)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadCheckpoints(self, request, context):
        """Load multiple checkpoints for parallel evaluation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NNInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Evaluate': grpc.unary_unary_rpc_method_handler(
                    servicer.Evaluate,
                    request_deserializer=inference__pb2.EvaluateRequest.FromString,
                    response_serializer=inference__pb2.EvaluateResponse.SerializeToString,
            ),
            'EvaluateBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateBatch,
                    request_deserializer=inference__pb2.EvaluateBatchRequest.FromString,
                    response_serializer=inference__pb2.EvaluateBatchResponse.SerializeToString,
            ),
            'ReloadCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.ReloadCheckpoint,
                    request_deserializer=inference__pb2.ReloadCheckpointRequest.FromString,
                    response_serializer=inference__pb2.ReloadCheckpointResponse.SerializeToString,
            ),
            'LoadCheckpoints': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadCheckpoints,
                    request_deserializer=inference__pb2.LoadCheckpointsRequest.FromString,
                    response_serializer=inference__pb2.LoadCheckpointsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'alpha_go.NNInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('alpha_go.NNInference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NNInference(object):
    """Neural network inference service for batched evaluation
    """

    @staticmethod
    def Evaluate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alpha_go.NNInference/Evaluate',
            inference__pb2.EvaluateRequest.SerializeToString,
            inference__pb2.EvaluateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvaluateBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alpha_go.NNInference/EvaluateBatch',
            inference__pb2.EvaluateBatchRequest.SerializeToString,
            inference__pb2.EvaluateBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReloadCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alpha_go.NNInference/ReloadCheckpoint',
            inference__pb2.ReloadCheckpointRequest.SerializeToString,
            inference__pb2.ReloadCheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadCheckpoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alpha_go.NNInference/LoadCheckpoints',
            inference__pb2.LoadCheckpointsRequest.SerializeToString,
            inference__pb2.LoadCheckpointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
